spring.application.name=weather-api

# openweather api key
openweather.api.key=${openweather-api}

# url for calling the geocoding endpoint
geocoding.service.url=http://api.openweathermap.org/geo/1.0/direct

# url for calling the weather endpoint
weather.service.url=https://api.openweathermap.org/data/2.5/weather